name: Build and release

on:
  push:
    branches: [ "master", "qt-workflow" ]

jobs:
  Build:

    runs-on: windows-latest
    
    strategy:
      fail-fast: false
    
      matrix:
        configuration: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          submodules: recursive
          
      - name: Cache Qt
        id: qt-cache
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.qt-cache.outputs.cache-hit }}
          version: 6.3.1
          setup-python: false
          
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
          
      - name: Generate Makefiles
        run: |
          mkdir build
          cd build
          qmake ../SkylandersEditor.pro
          dir
          
      - name: Build
        run: |
          cd build
          nmake ${{ matrix.configuration }}
          
      - name: Copy binary
        run: |
          mkdir output
          cp build/${{ matrix.configuration }}/SkylandersEditor.exe output/SkylandersEditor.exe
          
      - name: Deploy
        run: |
          windeployqt --no-plugins --no-quick-import --no-translations --no-system-d3d-compiler --no-virtualkeyboard --no-compiler-runtime --no-opengl-sw --dir ./output/
          cd output
          dir
